#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
5-11月主题规划（继续）
"""

# ========== 5月：认知偏差与决策陷阱（31篇）==========
MAY_TOPICS = {
    "2025-05-01": {
        "title": "认知偏差地图：25种交易陷阱",
        "slug": "cognitive-bias-map",
        "author_perspective": "Charlie Munger",
        "tags": ["认知偏差", "误判心理学", "系统化"],
        "key_concepts": ["Cognitive Biases", "Systematic Errors", "Mental Models"],
        "case_study": "芒格的检查清单方法",
    },
    "2025-05-02": {
        "title": "近因效应：最近的不等于最重要的",
        "slug": "recency-effect",
        "author_perspective": "Daniel Kahneman",
        "tags": ["近因效应", "记忆偏差", "权重扭曲"],
        "key_concepts": ["Recency Effect", "Memory Bias", "Weight Distortion"],
        "case_study": "\"最近三天都涨，明天肯定跌\"",
    },
    "2025-05-03": {
        "title": "后见之明偏差：\"我早就知道\"",
        "slug": "hindsight-bias",
        "author_perspective": "Daniel Kahneman",
        "tags": ["后见之明", "知识幻觉", "学习障碍"],
        "key_concepts": ["Hindsight Bias", "I-Knew-It-All-Along", "Learning Obstacle"],
        "case_study": "\"我就说它会跌\"（其实事前没说）",
    },
    "2025-05-04": {
        "title": "叙事谬误：市场不是故事书",
        "slug": "narrative-fallacy",
        "author_perspective": "Nassim Taleb",
        "tags": ["叙事谬误", "因果幻觉", "故事偏好"],
        "key_concepts": ["Narrative Fallacy", "Causality Illusion", "Story Preference"],
        "case_study": "为随机波动编造\"逻辑\"",
    },
    "2025-05-05": {
        "title": "选择性记忆：只记得对的预测",
        "slug": "selective-memory",
        "author_perspective": "Charlie Munger",
        "tags": ["选择性记忆", "自我欺骗", "记录重要性"],
        "key_concepts": ["Selective Memory", "Self-Deception", "Record Keeping"],
        "case_study": "股评家的\"神准\"秘密",
    },
    "2025-05-06": {
        "title": "基础率谬误：忽视大概率",
        "slug": "base-rate-fallacy",
        "author_perspective": "Daniel Kahneman",
        "tags": ["基础率", "统计盲区", "个案偏见"],
        "key_concepts": ["Base Rate Neglect", "Statistical Blindness", "Individual Case Bias"],
        "case_study": "\"某某炒股赚了千万\"（忽视90%亏损率）",
    },
    "2025-05-07": {
        "title": "合取谬误：越详细越不可能",
        "slug": "conjunction-fallacy",
        "author_perspective": "Daniel Kahneman",
        "tags": ["合取谬误", "概率错觉", "叙事诱惑"],
        "key_concepts": ["Conjunction Fallacy", "Probability Illusion", "Narrative Seduction"],
        "case_study": "复杂的\"逻辑链\"vs简单的概率",
    },
    "2025-05-08": {
        "title": "赌徒谬误：\"该我赢了\"",
        "slug": "gamblers-fallacy",
        "author_perspective": "Daniel Kahneman",
        "tags": ["赌徒谬误", "均值回归", "独立事件"],
        "key_concepts": ["Gambler's Fallacy", "Mean Reversion", "Independent Events"],
        "case_study": "\"连续5次止损,第6次肯定盈利\"",
    },
    "2025-05-09": {
        "title": "热手谬误：\"手风顺\"的幻觉",
        "slug": "hot-hand-fallacy",
        "author_perspective": "Daniel Kahneman",
        "tags": ["热手谬误", "随机性误读", "过度自信"],
        "key_concepts": ["Hot Hand Fallacy", "Randomness Misinterpretation", "Overconfidence"],
        "case_study": "\"连赢3笔，加大仓位\"",
    },
    "2025-05-10": {
        "title": "归因错误：内归成功，外归失败",
        "slug": "attribution-error",
        "author_perspective": "社会心理学",
        "tags": ["归因错误", "自我服务偏差", "责任逃避"],
        "key_concepts": ["Attribution Error", "Self-Serving Bias", "Responsibility Avoidance"],
        "case_study": "\"赚是我牛，亏是市场差\"",
    },
    "2025-05-11": {
        "title": "过度自信的三个维度",
        "slug": "three-dimensions-overconfidence",
        "author_perspective": "Charlie Munger",
        "tags": ["过度自信", "能力错觉", "控制幻觉"],
        "key_concepts": ["Overconfidence", "Illusion of Competence", "Illusion of Control"],
        "case_study": "\"我不一样\"综合症",
    },
    "2025-05-12": {
        "title": "专业知识的诅咒",
        "slug": "curse-of-expertise",
        "author_perspective": "Brett Steenbarger",
        "tags": ["专业陷阱", "僵化思维", "新手心态"],
        "key_concepts": ["Expertise Curse", "Mental Rigidity", "Beginner's Mind"],
        "case_study": "\"老手\"为何常败给市场",
    },
    "2025-05-13": {
        "title": "互惠倾向：\"投桃报李\"的陷阱",
        "slug": "reciprocity-trap",
        "author_perspective": "Robert Cialdini",
        "tags": ["互惠原理", "社交债务", "营销陷阱"],
        "key_concepts": ["Reciprocity", "Social Debt", "Marketing Trap"],
        "case_study": "\"免费\"荐股背后的心机",
    },
    "2025-05-14": {
        "title": "承诺一致性：死要面子",
        "slug": "commitment-consistency",
        "author_perspective": "Robert Cialdini",
        "tags": ["承诺一致", "面子心理", "路径依赖"],
        "key_concepts": ["Commitment Consistency", "Face Psychology", "Path Dependence"],
        "case_study": "\"我说过看好这股票\"（所以不能卖）",
    },
    "2025-05-15": {
        "title": "社会认同：\"大家都在买\"",
        "slug": "social-proof-trading",
        "author_perspective": "Robert Cialdini",
        "tags": ["社会认同", "从众压力", "信息瀑布"],
        "key_concepts": ["Social Proof", "Conformity Pressure", "Information Cascade"],
        "case_study": "\"龙头股\"的社会认同机制",
    },
    "2025-05-16": {
        "title": "喜好原理：\"这个老师我喜欢\"",
        "slug": "liking-principle",
        "author_perspective": "Robert Cialdini",
        "tags": ["喜好原理", "人格魅力", "判断失误"],
        "key_concepts": ["Liking Principle", "Charisma", "Judgment Error"],
        "case_study": "为何\"网红\"荐股总有人信",
    },
    "2025-05-17": {
        "title": "权威服从：\"专家说的\"",
        "slug": "authority-obedience",
        "author_perspective": "Robert Cialdini",
        "tags": ["权威服从", "米尔格拉姆实验", "盲从"],
        "key_concepts": ["Authority Obedience", "Milgram Experiment", "Blind Following"],
        "case_study": "\"某某经济学家预测...\"",
    },
    "2025-05-18": {
        "title": "稀缺性原理：\"最后机会\"",
        "slug": "scarcity-principle",
        "author_perspective": "Robert Cialdini",
        "tags": ["稀缺性", "限时限量", "FOMO"],
        "key_concepts": ["Scarcity", "Limited Time", "FOMO"],
        "case_study": "\"今天不买明天涨停\"",
    },
    "2025-05-19": {
        "title": "对比原理：参照物陷阱",
        "slug": "contrast-principle",
        "author_perspective": "Robert Cialdini",
        "tags": ["对比原理", "参照系", "价格锚定"],
        "key_concepts": ["Contrast Principle", "Reference Frame", "Price Anchoring"],
        "case_study": "\"都跌30%了，够便宜了\"",
    },
    "2025-05-20": {
        "title": "群体极化：聊天室的疯狂",
        "slug": "group-polarization",
        "author_perspective": "社会心理学",
        "tags": ["群体极化", "回音室", "极端化"],
        "key_concepts": ["Group Polarization", "Echo Chamber", "Extremization"],
        "case_study": "股吧如何制造共识幻觉",
    },
    "2025-05-21": {
        "title": "信息茧房：算法的温柔陷阱",
        "slug": "filter-bubble",
        "author_perspective": "综合",
        "tags": ["信息茧房", "算法推荐", "认知封闭"],
        "key_concepts": ["Filter Bubble", "Algorithm Recommendation", "Cognitive Closure"],
        "case_study": "为何你总刷到\"牛市来了\"",
    },
    "2025-05-22": {
        "title": "鸵鸟效应：\"不看就不亏\"",
        "slug": "ostrich-effect",
        "author_perspective": "行为金融学",
        "tags": ["鸵鸟效应", "选择性忽视", "逃避"],
        "key_concepts": ["Ostrich Effect", "Selective Ignorance", "Avoidance"],
        "case_study": "大跌时不看账户",
    },
    "2025-05-23": {
        "title": "心理账户：钱不等于钱",
        "slug": "mental-accounting",
        "author_perspective": "Richard Thaler",
        "tags": ["心理账户", "资金隔离", "非理性"],
        "key_concepts": ["Mental Accounting", "Fund Segregation", "Irrationality"],
        "case_study": "\"工资钱不敢亏，奖金钱随便赌\"",
    },
    "2025-05-24": {
        "title": "交易账户的分类陷阱",
        "slug": "account-categorization-trap",
        "author_perspective": "Richard Thaler",
        "tags": ["账户分类", "心理隔离", "风险错配"],
        "key_concepts": ["Account Categorization", "Mental Segregation", "Risk Mismatch"],
        "case_study": "\"本金\"vs\"盈利\"的不同对待",
    },
    "2025-05-25": {
        "title": "框架依赖：说法改变，决策改变",
        "slug": "framing-dependence",
        "author_perspective": "Daniel Kahneman",
        "tags": ["框架依赖", "表述效应", "非理性"],
        "key_concepts": ["Framing Dependence", "Presentation Effect", "Irrationality"],
        "case_study": "\"90%胜率\"vs\"10%失败率\"",
    },
    "2025-05-26": {
        "title": "现状偏见：\"不动最安全\"",
        "slug": "status-quo-bias",
        "author_perspective": "行为经济学",
        "tags": ["现状偏见", "惰性", "损失厌恶"],
        "key_concepts": ["Status Quo Bias", "Inertia", "Loss Aversion"],
        "case_study": "\"反正都套了，就放着吧\"",
    },
    "2025-05-27": {
        "title": "注意力偏差：你看见你想看见的",
        "slug": "attention-bias",
        "author_perspective": "认知心理学",
        "tags": ["注意力偏差", "选择性注意", "信息过滤"],
        "key_concepts": ["Attention Bias", "Selective Attention", "Information Filtering"],
        "case_study": "为何总能\"找到\"支持自己的信息",
    },
    "2025-05-28": {
        "title": "中国市场的特色偏差",
        "slug": "china-market-specific-biases",
        "author_perspective": "综合",
        "tags": ["中国特色", "文化偏差", "市场生态"],
        "key_concepts": ["China-Specific", "Cultural Biases", "Market Ecology"],
        "case_study": "\"庄家思维\"的认知根源",
    },
    "2025-05-29": {
        "title": "政策依赖症：\"等救市\"心理",
        "slug": "policy-dependence",
        "author_perspective": "综合",
        "tags": ["政策依赖", "外部归因", "被动心态"],
        "key_concepts": ["Policy Dependence", "External Attribution", "Passive Mindset"],
        "case_study": "\"国家队会护盘\"",
    },
    "2025-05-30": {
        "title": "偏差的偏差：\"我没有偏差\"",
        "slug": "bias-blind-spot",
        "author_perspective": "Emily Pronin",
        "tags": ["偏差盲点", "自我例外", "元认知"],
        "key_concepts": ["Bias Blind Spot", "Self-Exception", "Metacognition"],
        "case_study": "\"别人有偏见，我很客观\"",
    },
    "2025-05-31": {
        "title": "5月总结：绘制你的认知地雷图",
        "slug": "may-summary-cognitive-minefield",
        "author_perspective": "综合",
        "tags": ["月度总结", "偏差地图", "个人清单"],
        "key_concepts": ["Summary", "Bias Map", "Personal Checklist"],
        "case_study": "你最容易犯的前5个偏差",
    },
}

# ========== 6月：最佳流程与绩效优化（30篇）==========
JUNE_TOPICS = {
    "2025-06-01": {
        "title": "从Best Practices到Best Processes",
        "slug": "practices-to-processes",
        "author_perspective": "Brett Steenbarger",
        "tags": ["最佳流程", "Trading Psychology 2.0", "系统化"],
        "key_concepts": ["Best Processes", "Systematic Approach", "Continuous Improvement"],
        "case_study": "为什么模仿大师的做法没用",
    },
    "2025-06-02": {
        "title": "交易流程的解剖学",
        "slug": "trading-process-anatomy",
        "author_perspective": "Brett Steenbarger",
        "tags": ["流程设计", "系统架构", "模块化"],
        "key_concepts": ["Process Design", "System Architecture", "Modularity"],
        "case_study": "一笔交易的12个心理节点",
    },
    "2025-06-03": {
        "title": "绩效指标：不只是盈亏比",
        "slug": "performance-metrics-beyond-pnl",
        "author_perspective": "Brett Steenbarger",
        "tags": ["绩效指标", "多维评估", "过程导向"],
        "key_concepts": ["Performance Metrics", "Multi-Dimensional Assessment", "Process Orientation"],
        "case_study": "优秀交易者追踪的15个指标",
    },
    "2025-06-04": {
        "title": "执行质量评分系统",
        "slug": "execution-quality-scoring",
        "author_perspective": "Brett Steenbarger",
        "tags": ["执行质量", "评分系统", "自我评估"],
        "key_concepts": ["Execution Quality", "Scoring System", "Self-Assessment"],
        "case_study": "如何为每笔交易打分（1-10）",
    },
    "2025-06-05": {
        "title": "刻意练习在交易中的应用",
        "slug": "deliberate-practice-trading",
        "author_perspective": "Anders Ericsson理论",
        "tags": ["刻意练习", "技能习得", "专家养成"],
        "key_concepts": ["Deliberate Practice", "Skill Acquisition", "Expertise Development"],
        "case_study": "10000小时vs 10000次反思",
    },
    "2025-06-06": {
        "title": "反馈循环的设计",
        "slug": "feedback-loop-design",
        "author_perspective": "Brett Steenbarger",
        "tags": ["反馈循环", "持续改进", "学习系统"],
        "key_concepts": ["Feedback Loop", "Continuous Improvement", "Learning System"],
        "case_study": "日复盘→周复盘→月复盘体系",
    },
    "2025-06-07": {
        "title": "前瞻性复盘vs回顾性复盘",
        "slug": "prospective-vs-retrospective-review",
        "author_perspective": "Brett Steenbarger",
        "tags": ["复盘方法", "预演", "反思"],
        "key_concepts": ["Review Methods", "Mental Rehearsal", "Reflection"],
        "case_study": "\"如果明天再遇到，我会...\"",
    },
    "2025-06-08": {
        "title": "错误分类系统",
        "slug": "error-classification-system",
        "author_perspective": "Jared Tendler",
        "tags": ["错误分类", "问题诊断", "针对性改进"],
        "key_concepts": ["Error Classification", "Problem Diagnosis", "Targeted Improvement"],
        "case_study": "技术错误vs心理错误vs系统错误",
    },
    "2025-06-09": {
        "title": "心理状态监测仪表盘",
        "slug": "psychological-state-dashboard",
        "author_perspective": "Brett Steenbarger",
        "tags": ["状态监测", "实时反馈", "早期预警"],
        "key_concepts": ["State Monitoring", "Real-time Feedback", "Early Warning"],
        "case_study": "5个指标判断你是否该交易",
    },
    "2025-06-10": {
        "title": "交易准备流程的标准化",
        "slug": "trading-preparation-standardization",
        "author_perspective": "Brett Steenbarger",
        "tags": ["准备流程", "标准化", "仪式感"],
        "key_concepts": ["Preparation Process", "Standardization", "Ritual"],
        "case_study": "开盘前90分钟的固定流程",
    },
    "2025-06-11": {
        "title": "盘中决策流程图",
        "slug": "intraday-decision-flowchart",
        "author_perspective": "Mark Douglas",
        "tags": ["决策流程", "标准化", "减少犹豫"],
        "key_concepts": ["Decision Process", "Standardization", "Hesitation Reduction"],
        "case_study": "从信号到执行的6步检查",
    },
    "2025-06-12": {
        "title": "盘后复盘的三层结构",
        "slug": "three-layer-review",
        "author_perspective": "Brett Steenbarger",
        "tags": ["复盘结构", "多层次", "深度挖掘"],
        "key_concepts": ["Review Structure", "Multi-Layer", "Deep Excavation"],
        "case_study": "事实层→模式层→信念层",
    },
    "2025-06-13": {
        "title": "绩效基线的建立",
        "slug": "performance-baseline-establishment",
        "author_perspective": "Brett Steenbarger",
        "tags": ["绩效基线", "自我比较", "进步追踪"],
        "key_concepts": ["Performance Baseline", "Self-Comparison", "Progress Tracking"],
        "case_study": "\"当前的我\"vs\"30天前的我\"",
    },
    "2025-06-14": {
        "title": "改进实验：A/B测试心理技巧",
        "slug": "improvement-experiments",
        "author_perspective": "Brett Steenbarger",
        "tags": ["实验方法", "AB测试", "数据驱动"],
        "key_concepts": ["Experimental Method", "AB Testing", "Data-Driven"],
        "case_study": "测试不同的止损方法对心理的影响",
    },
    "2025-06-15": {
        "title": "心理技能的分项训练",
        "slug": "mental-skill-component-training",
        "author_perspective": "Jared Tendler",
        "tags": ["分项训练", "技能拆解", "专项提升"],
        "key_concepts": ["Component Training", "Skill Decomposition", "Targeted Improvement"],
        "case_study": "单独训练：冲动控制、耐心、专注",
    },
    "2025-06-16": {
        "title": "压力测试：模拟极端情境",
        "slug": "stress-testing-extreme-scenarios",
        "author_perspective": "Brett Steenbarger",
        "tags": ["压力测试", "极端情境", "心理韧性"],
        "key_concepts": ["Stress Testing", "Extreme Scenarios", "Psychological Resilience"],
        "case_study": "\"如果连续止损10次，我会...\"",
    },
    "2025-06-17": {
        "title": "峰态绩效的复制公式",
        "slug": "peak-performance-replication",
        "author_perspective": "Brett Steenbarger",
        "tags": ["峰态绩效", "最佳状态", "复制系统"],
        "key_concepts": ["Peak Performance", "Optimal State", "Replication System"],
        "case_study": "你最佳交易日的10个共同点",
    },
    "2025-06-18": {
        "title": "低谷期的流程维护",
        "slug": "process-maintenance-slump",
        "author_perspective": "Jared Tendler",
        "tags": ["低谷期", "流程坚持", "心理韧性"],
        "key_concepts": ["Slump Period", "Process Adherence", "Psychological Resilience"],
        "case_study": "连续亏损时如何不乱套",
    },
    "2025-06-19": {
        "title": "交易日志的进化：从记录到洞察",
        "slug": "trading-journal-evolution",
        "author_perspective": "Brett Steenbarger",
        "tags": ["交易日志", "进化", "深度分析"],
        "key_concepts": ["Trading Journal", "Evolution", "Deep Analysis"],
        "case_study": "第一代日志vs第三代日志",
    },
    "2025-06-20": {
        "title": "视频复盘：重温你的交易瞬间",
        "slug": "video-review-trading-moments",
        "author_perspective": "Brett Steenbarger",
        "tags": ["视频复盘", "屏幕录制", "行为分析"],
        "key_concepts": ["Video Review", "Screen Recording", "Behavior Analysis"],
        "case_study": "录下你的盘中反应",
    },
    "2025-06-21": {
        "title": "语音日志：捕捉即时想法",
        "slug": "voice-journaling-immediate-thoughts",
        "author_perspective": "Denise Shull",
        "tags": ["语音日志", "即时记录", "情绪捕捉"],
        "key_concepts": ["Voice Journaling", "Immediate Recording", "Emotion Capture"],
        "case_study": "\"我现在感觉...\"（盘中录音）",
    },
    "2025-06-22": {
        "title": "同伴学习：交易伙伴系统",
        "slug": "peer-learning-trading-partner",
        "author_perspective": "Brett Steenbarger",
        "tags": ["同伴学习", "互助", "问责制"],
        "key_concepts": ["Peer Learning", "Mutual Support", "Accountability"],
        "case_study": "找一个每日互相复盘的伙伴",
    },
    "2025-06-23": {
        "title": "导师制：加速学习曲线",
        "slug": "mentorship-accelerated-learning",
        "author_perspective": "Brett Steenbarger",
        "tags": ["导师制", "加速学习", "经验传承"],
        "key_concepts": ["Mentorship", "Accelerated Learning", "Experience Transfer"],
        "case_study": "好导师vs坏导师的区别",
    },
    "2025-06-24": {
        "title": "模拟盘的正确使用",
        "slug": "sim-trading-correct-use",
        "author_perspective": "Brett Steenbarger",
        "tags": ["模拟盘", "心理训练", "技能迁移"],
        "key_concepts": ["Sim Trading", "Psychological Training", "Skill Transfer"],
        "case_study": "为什么模拟盘赚钱实盘亏钱",
    },
    "2025-06-25": {
        "title": "渐进式真实化：从模拟到实盘",
        "slug": "progressive-realization",
        "author_perspective": "Brett Steenbarger",
        "tags": ["渐进式", "真实化", "心理过渡"],
        "key_concepts": ["Progressive", "Realization", "Psychological Transition"],
        "case_study": "1%仓位→5%→10%的过渡策略",
    },
    "2025-06-26": {
        "title": "数据驱动的自我认知",
        "slug": "data-driven-self-knowledge",
        "author_perspective": "Brett Steenbarger",
        "tags": ["数据驱动", "自我认知", "客观分析"],
        "key_concepts": ["Data-Driven", "Self-Knowledge", "Objective Analysis"],
        "case_study": "100笔交易数据告诉你的真相",
    },
    "2025-06-27": {
        "title": "流程审计：定期系统检查",
        "slug": "process-audit-periodic-review",
        "author_perspective": "Brett Steenbarger",
        "tags": ["流程审计", "系统检查", "持续优化"],
        "key_concepts": ["Process Audit", "System Review", "Continuous Optimization"],
        "case_study": "每月第一个周末的流程大检查",
    },
    "2025-06-28": {
        "title": "中国交易者的流程障碍",
        "slug": "chinese-traders-process-obstacles",
        "author_perspective": "综合",
        "tags": ["文化障碍", "流程困难", "系统化"],
        "key_concepts": ["Cultural Obstacles", "Process Difficulty", "Systemization"],
        "case_study": "为何中国人觉得\"系统化\"太死板",
    },
    "2025-06-29": {
        "title": "灵活性与纪律性的平衡",
        "slug": "flexibility-discipline-balance",
        "author_perspective": "Brett Steenbarger",
        "tags": ["灵活性", "纪律性", "动态平衡"],
        "key_concepts": ["Flexibility", "Discipline", "Dynamic Balance"],
        "case_study": "何时坚持流程，何时调整流程",
    },
    "2025-06-30": {
        "title": "6月总结：搭建你的绩效优化系统",
        "slug": "june-summary-performance-system",
        "author_perspective": "综合",
        "tags": ["月度总结", "绩效系统", "流程整合"],
        "key_concepts": ["Summary", "Performance System", "Process Integration"],
        "case_study": "你的个人交易绩效仪表盘",
    },
}

# ========== 7月：风险认知与仓位管理心理（31篇）==========
JULY_TOPICS = {
    "2025-07-01": {
        "title": "风险的主观性：你以为的不是真的",
        "slug": "risk-subjectivity",
        "author_perspective": "Denise Shull",
        "tags": ["风险主观性", "感知vs现实", "校准"],
        "key_concepts": ["Risk Subjectivity", "Perception vs Reality", "Calibration"],
        "case_study": "为什么散户总觉得\"稳了\"时最危险",
    },
    "2025-07-02": {
        "title": "风险vs不确定性：奈特区分",
        "slug": "risk-vs-uncertainty-knight",
        "author_perspective": "经济学理论",
        "tags": ["风险", "不确定性", "可量化"],
        "key_concepts": ["Risk", "Uncertainty", "Quantifiability"],
        "case_study": "黑天鹅属于哪一类",
    },
    "2025-07-03": {
        "title": "R倍数思维：统一风险语言",
        "slug": "r-multiple-thinking",
        "author_perspective": "Van Tharp",
        "tags": ["R倍数", "风险统一", "盈亏比"],
        "key_concepts": ["R-Multiple", "Risk Unification", "Risk-Reward Ratio"],
        "case_study": "\"赚了5R\"比\"赚了5000\"更重要",
    },
    "2025-07-04": {
        "title": "仓位大小的心理学",
        "slug": "position-sizing-psychology",
        "author_perspective": "Mark Douglas",
        "tags": ["仓位管理", "心理负荷", "舒适区"],
        "key_concepts": ["Position Sizing", "Psychological Load", "Comfort Zone"],
        "case_study": "\"重仓\"如何摧毁执行力",
    },
    "2025-07-05": {
        "title": "凯利公式的心理陷阱",
        "slug": "kelly-criterion-psychological-trap",
        "author_perspective": "行为金融学",
        "tags": ["凯利公式", "最优仓位", "心理承受"],
        "key_concepts": ["Kelly Criterion", "Optimal Position", "Psychological Tolerance"],
        "case_study": "数学最优≠心理最优",
    },
    "2025-07-06": {
        "title": "固定仓位vs固定风险",
        "slug": "fixed-position-vs-fixed-risk",
        "author_perspective": "Van Tharp",
        "tags": ["仓位策略", "风险控制", "心理稳定"],
        "key_concepts": ["Position Strategy", "Risk Control", "Psychological Stability"],
        "case_study": "为什么固定风险更优",
    },
    "2025-07-07": {
        "title": "账户波动率与心理健康",
        "slug": "account-volatility-mental-health",
        "author_perspective": "Denise Shull",
        "tags": ["账户波动", "心理健康", "压力管理"],
        "key_concepts": ["Account Volatility", "Mental Health", "Stress Management"],
        "case_study": "\"过山车\"行情对睡眠的影响",
    },
    "2025-07-08": {
        "title": "最大回撤的心理意义",
        "slug": "maximum-drawdown-psychology",
        "author_perspective": "Brett Steenbarger",
        "tags": ["最大回撤", "心理极限", "韧性测试"],
        "key_concepts": ["Maximum Drawdown", "Psychological Limit", "Resilience Test"],
        "case_study": "你能承受多少连续亏损",
    },
    "2025-07-09": {
        "title": "破产风险的真实恐惧",
        "slug": "ruin-risk-real-fear",
        "author_perspective": "Nassim Taleb",
        "tags": ["破产风险", "存活第一", "黑天鹅"],
        "key_concepts": ["Ruin Risk", "Survival First", "Black Swan"],
        "case_study": "\"归零\"的心理创伤",
    },
    "2025-07-10": {
        "title": "止损幅度与心理承受",
        "slug": "stop-loss-size-psychology",
        "author_perspective": "Mark Douglas",
        "tags": ["止损幅度", "心理承受", "舒适度"],
        "key_concepts": ["Stop Loss Size", "Psychological Tolerance", "Comfort"],
        "case_study": "3%止损vs10%止损的心理差异",
    },
    "2025-07-11": {
        "title": "分散vs集中：风险的悖论",
        "slug": "diversification-vs-concentration",
        "author_perspective": "Charlie Munger",
        "tags": ["分散投资", "集中持仓", "风险管理"],
        "key_concepts": ["Diversification", "Concentration", "Risk Management"],
        "case_study": "\"鸡蛋\"该放几个篮子",
    },
    "2025-07-12": {
        "title": "相关性陷阱：虚假的分散",
        "slug": "correlation-trap",
        "author_perspective": "Nassim Taleb",
        "tags": ["相关性", "虚假分散", "系统性风险"],
        "key_concepts": ["Correlation", "False Diversification", "Systematic Risk"],
        "case_study": "\"买了5只券商股\"不是分散",
    },
    "2025-07-13": {
        "title": "杠杆的心理放大器效应",
        "slug": "leverage-psychological-amplifier",
        "author_perspective": "Denise Shull",
        "tags": ["杠杆", "心理放大", "情绪波动"],
        "key_concepts": ["Leverage", "Psychological Amplification", "Emotional Volatility"],
        "case_study": "融资融券如何改变你的性格",
    },
    "2025-07-14": {
        "title": "\"赌一把\"心理的风险失控",
        "slug": "gamble-mentality-risk-runaway",
        "author_perspective": "Jared Tendler",
        "tags": ["赌博心态", "风险失控", "全押"],
        "key_concepts": ["Gambling Mentality", "Risk Runaway", "All-in"],
        "case_study": "\"这次一定要翻本\"",
    },
    "2025-07-15": {
        "title": "风险预算：给风险分配额度",
        "slug": "risk-budgeting",
        "author_perspective": "机构投资理论",
        "tags": ["风险预算", "额度管理", "理性分配"],
        "key_concepts": ["Risk Budgeting", "Quota Management", "Rational Allocation"],
        "case_study": "每月只能亏损账户的5%",
    },
    "2025-07-16": {
        "title": "仓位与情绪的正反馈循环",
        "slug": "position-emotion-feedback-loop",
        "author_perspective": "Denise Shull",
        "tags": ["正反馈", "仓位情绪", "恶性循环"],
        "key_concepts": ["Positive Feedback", "Position Emotion", "Vicious Cycle"],
        "case_study": "重仓→焦虑→错误→更焦虑",
    },
    "2025-07-17": {
        "title": "加仓的心理学：何时该加",
        "slug": "pyramiding-psychology",
        "author_perspective": "Mark Douglas",
        "tags": ["加仓", "金字塔", "风险控制"],
        "key_concepts": ["Pyramiding", "Adding Positions", "Risk Control"],
        "case_study": "盈利加仓vs浮亏摊平",
    },
    "2025-07-18": {
        "title": "减仓的艺术：主动风险管理",
        "slug": "position-reduction-art",
        "author_perspective": "Brett Steenbarger",
        "tags": ["减仓", "主动管理", "灵活应对"],
        "key_concepts": ["Position Reduction", "Active Management", "Flexible Response"],
        "case_study": "\"感觉不对时\"减半仓位",
    },
    "2025-07-19": {
        "title": "全仓vs分批：不同的心理体验",
        "slug": "lump-sum-vs-averaging",
        "author_perspective": "行为金融学",
        "tags": ["全仓", "分批", "心理差异"],
        "key_concepts": ["Lump Sum", "Dollar Cost Averaging", "Psychological Difference"],
        "case_study": "为什么\"分批买入\"更舒服",
    },
    "2025-07-20": {
        "title": "风险耐受度测试：认识真实的你",
        "slug": "risk-tolerance-testing",
        "author_perspective": "Denise Shull",
        "tags": ["风险耐受", "自我测试", "真实认知"],
        "key_concepts": ["Risk Tolerance", "Self-Testing", "Real Understanding"],
        "case_study": "问卷vs真实亏损的差异",
    },
    "2025-07-21": {
        "title": "风险与年龄：生命周期视角",
        "slug": "risk-age-lifecycle",
        "author_perspective": "理财心理学",
        "tags": ["年龄", "生命周期", "风险配置"],
        "key_concepts": ["Age", "Lifecycle", "Risk Allocation"],
        "case_study": "25岁vs55岁的风险承受力",
    },
    "2025-07-22": {
        "title": "风险与资金来源：钱的\"温度\"",
        "slug": "risk-fund-source",
        "author_perspective": "Richard Thaler",
        "tags": ["资金来源", "心理账户", "风险态度"],
        "key_concepts": ["Fund Source", "Mental Accounting", "Risk Attitude"],
        "case_study": "\"闲钱\"vs\"借钱\"的不同心态",
    },
    "2025-07-23": {
        "title": "风险补偿：高风险=高回报？",
        "slug": "risk-compensation-fallacy",
        "author_perspective": "行为金融学",
        "tags": ["风险补偿", "回报预期", "认知误区"],
        "key_concepts": ["Risk Compensation", "Return Expectation", "Cognitive Error"],
        "case_study": "\"ST股跌多了该涨了\"",
    },
    "2025-07-24": {
        "title": "安全边际：巴菲特的风险哲学",
        "slug": "margin-of-safety",
        "author_perspective": "价值投资",
        "tags": ["安全边际", "价值投资", "风险缓冲"],
        "key_concepts": ["Margin of Safety", "Value Investing", "Risk Buffer"],
        "case_study": "\"打五折买\"的心理安全感",
    },
    "2025-07-25": {
        "title": "风险的时间维度",
        "slug": "risk-time-dimension",
        "author_perspective": "综合",
        "tags": ["时间维度", "短期vs长期", "风险演化"],
        "key_concepts": ["Time Dimension", "Short vs Long Term", "Risk Evolution"],
        "case_study": "日内风险vs持仓过夜风险",
    },
    "2025-07-26": {
        "title": "中国市场的特殊风险",
        "slug": "china-market-specific-risks",
        "author_perspective": "综合",
        "tags": ["中国特色", "政策风险", "系统性"],
        "key_concepts": ["China-Specific", "Policy Risk", "Systematic"],
        "case_study": "\"退市\"恐慌的心理冲击",
    },
    "2025-07-27": {
        "title": "\"保本\"心理的风险悖论",
        "slug": "capital-preservation-paradox",
        "author_perspective": "行为金融学",
        "tags": ["保本心理", "风险悖论", "机会成本"],
        "key_concepts": ["Capital Preservation", "Risk Paradox", "Opportunity Cost"],
        "case_study": "\"不能亏本金\"导致更大亏损",
    },
    "2025-07-28": {
        "title": "尾部风险：1%的事件，99%的影响",
        "slug": "tail-risk",
        "author_perspective": "Nassim Taleb",
        "tags": ["尾部风险", "极端事件", "黑天鹅"],
        "key_concepts": ["Tail Risk", "Extreme Events", "Black Swan"],
        "case_study": "2015年熔断的意外冲击",
    },
    "2025-07-29": {
        "title": "风险对冲的心理成本",
        "slug": "hedging-psychological-cost",
        "author_perspective": "行为金融学",
        "tags": ["风险对冲", "心理成本", "保险心理"],
        "key_concepts": ["Hedging", "Psychological Cost", "Insurance Psychology"],
        "case_study": "\"买了保险不出事就亏了\"",
    },
    "2025-07-30": {
        "title": "风险沟通：如何对家人解释",
        "slug": "risk-communication-family",
        "author_perspective": "综合",
        "tags": ["风险沟通", "家庭关系", "理解差异"],
        "key_concepts": ["Risk Communication", "Family Relations", "Understanding Gap"],
        "case_study": "\"你在赌博\"vs\"我在管理风险\"",
    },
    "2025-07-31": {
        "title": "7月总结：建立你的风险框架",
        "slug": "july-summary-risk-framework",
        "author_perspective": "综合",
        "tags": ["月度总结", "风险框架", "个人系统"],
        "key_concepts": ["Summary", "Risk Framework", "Personal System"],
        "case_study": "你的风险管理宪法",
    },
}

# 导出所有主题
ALL_TOPICS = {}
ALL_TOPICS.update(MAY_TOPICS)
ALL_TOPICS.update(JUNE_TOPICS)
ALL_TOPICS.update(JULY_TOPICS)

if __name__ == "__main__":
    print(f"5-7月主题总数: {len(ALL_TOPICS)}")
    print(f"5月: {len(MAY_TOPICS)}")
    print(f"6月: {len(JUNE_TOPICS)}")
    print(f"7月: {len(JULY_TOPICS)}")
