#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
8-11月主题规划
"""

# ========== 8月：信念系统与交易哲学（31篇）==========
AUGUST_TOPICS = {
    "2025-08-01": {
        "title": "信念：交易世界的操作系统",
        "slug": "beliefs-operating-system",
        "author_perspective": "Mark Douglas",
        "tags": ["信念系统", "底层逻辑", "世界观"],
        "key_concepts": ["Belief System", "Underlying Logic", "Worldview"],
        "case_study": "为什么两个人看同一K线做出相反决策",
    },
    "2025-08-02": {
        "title": "交易者的五大核心信念",
        "slug": "five-core-beliefs",
        "author_perspective": "Mark Douglas",
        "tags": ["核心信念", "Trading in the Zone", "心智模式"],
        "key_concepts": ["Core Beliefs", "Mental Models", "Mindset"],
        "case_study": "从\"预测\"到\"概率\"的信念转变",
    },
    "2025-08-03": {
        "title": "限制性信念的识别",
        "slug": "limiting-beliefs-identification",
        "author_perspective": "Jared Tendler",
        "tags": ["限制性信念", "自我设限", "突破"],
        "key_concepts": ["Limiting Beliefs", "Self-Imposed Limits", "Breakthrough"],
        "case_study": "\"我不可能稳定盈利\"的自证预言",
    },
    "2025-08-04": {
        "title": "支持性信念的建立",
        "slug": "supportive-beliefs-building",
        "author_perspective": "Mark Douglas",
        "tags": ["支持性信念", "赋能", "积极心态"],
        "key_concepts": ["Supportive Beliefs", "Empowerment", "Positive Mindset"],
        "case_study": "\"我是概率的执行者\"",
    },
    "2025-08-05": {
        "title": "关于市场的信念",
        "slug": "beliefs-about-market",
        "author_perspective": "综合",
        "tags": ["市场本质", "信念影响", "认知框架"],
        "key_concepts": ["Market Nature", "Belief Impact", "Cognitive Framework"],
        "case_study": "\"市场是随机的\"vs\"市场被操纵\"",
    },
    "2025-08-06": {
        "title": "关于自己的信念",
        "slug": "beliefs-about-self",
        "author_perspective": "心理学",
        "tags": ["自我信念", "自我效能", "潜力"],
        "key_concepts": ["Self-Belief", "Self-Efficacy", "Potential"],
        "case_study": "\"我配得上盈利吗\"",
    },
    "2025-08-07": {
        "title": "关于金钱的信念",
        "slug": "beliefs-about-money",
        "author_perspective": "理财心理学",
        "tags": ["金钱观", "财富信念", "心理账户"],
        "key_concepts": ["Money Beliefs", "Wealth Mindset", "Mental Accounting"],
        "case_study": "\"钱来得快去得快\"的魔咒",
    },
    "2025-08-08": {
        "title": "关于风险的信念",
        "slug": "beliefs-about-risk",
        "author_perspective": "Denise Shull",
        "tags": ["风险观", "安全感", "冒险精神"],
        "key_concepts": ["Risk Beliefs", "Sense of Security", "Risk-Taking Spirit"],
        "case_study": "\"冒险=鲁莽\"还是\"冒险=必要\"",
    },
    "2025-08-09": {
        "title": "关于成功的信念",
        "slug": "beliefs-about-success",
        "author_perspective": "心理学",
        "tags": ["成功观", "成就定义", "幸福感"],
        "key_concepts": ["Success Beliefs", "Achievement Definition", "Happiness"],
        "case_study": "\"不赚到100万就是失败\"",
    },
    "2025-08-10": {
        "title": "关于失败的信念",
        "slug": "beliefs-about-failure",
        "author_perspective": "成长心态",
        "tags": ["失败观", "学习机会", "韧性"],
        "key_concepts": ["Failure Beliefs", "Learning Opportunity", "Resilience"],
        "case_study": "\"失败=终结\"vs\"失败=反馈\"",
    },
    "2025-08-11": {
        "title": "信念的形成机制",
        "slug": "belief-formation-mechanism",
        "author_perspective": "认知心理学",
        "tags": ["信念形成", "经验塑造", "社会影响"],
        "key_concepts": ["Belief Formation", "Experience Shaping", "Social Influence"],
        "case_study": "一次大亏如何改变你的信念",
    },
    "2025-08-12": {
        "title": "信念的自我强化",
        "slug": "belief-self-reinforcement",
        "author_perspective": "Mark Douglas",
        "tags": ["自我强化", "确认偏差", "循环"],
        "key_concepts": ["Self-Reinforcement", "Confirmation Bias", "Loop"],
        "case_study": "\"市场针对我\"的循环证明",
    },
    "2025-08-13": {
        "title": "信念冲突：内在矛盾",
        "slug": "belief-conflicts",
        "author_perspective": "认知失调理论",
        "tags": ["信念冲突", "认知失调", "内在矛盾"],
        "key_concepts": ["Belief Conflict", "Cognitive Dissonance", "Internal Contradiction"],
        "case_study": "\"我要赚钱\"vs\"我不配赚钱\"",
    },
    "2025-08-14": {
        "title": "信念改变的五阶段",
        "slug": "five-stages-belief-change",
        "author_perspective": "变革心理学",
        "tags": ["信念改变", "阶段模型", "转化过程"],
        "key_concepts": ["Belief Change", "Stage Model", "Transformation Process"],
        "case_study": "从\"赌徒\"到\"交易者\"的信念进化",
    },
    "2025-08-15": {
        "title": "体验式信念改变",
        "slug": "experiential-belief-change",
        "author_perspective": "Mark Douglas",
        "tags": ["体验式", "实践改变", "证据积累"],
        "key_concepts": ["Experiential", "Practice Change", "Evidence Accumulation"],
        "case_study": "100次一致执行后的信念转变",
    },
    "2025-08-16": {
        "title": "认知重构技术",
        "slug": "cognitive-restructuring",
        "author_perspective": "认知行为疗法",
        "tags": ["认知重构", "信念重写", "ABC模型"],
        "key_concepts": ["Cognitive Restructuring", "Belief Rewriting", "ABC Model"],
        "case_study": "挑战\"我必须赢\"的信念",
    },
    "2025-08-17": {
        "title": "信念与身份认同",
        "slug": "beliefs-identity",
        "author_perspective": "自我心理学",
        "tags": ["身份认同", "自我概念", "角色"],
        "key_concepts": ["Identity", "Self-Concept", "Role"],
        "case_study": "\"我是交易者\"vs\"我在炒股\"",
    },
    "2025-08-18": {
        "title": "文化信念对交易的影响",
        "slug": "cultural-beliefs-trading",
        "author_perspective": "文化心理学",
        "tags": ["文化信念", "集体潜意识", "价值观"],
        "key_concepts": ["Cultural Beliefs", "Collective Unconscious", "Values"],
        "case_study": "中国式\"面子\"信念",
    },
    "2025-08-19": {
        "title": "家庭金钱脚本",
        "slug": "family-money-scripts",
        "author_perspective": "理财治疗",
        "tags": ["金钱脚本", "家庭影响", "童年经验"],
        "key_concepts": ["Money Scripts", "Family Influence", "Childhood Experience"],
        "case_study": "\"钱是万恶之源\"的童年烙印",
    },
    "2025-08-20": {
        "title": "\"庄家思维\"的信念解构",
        "slug": "market-maker-mindset-deconstruction",
        "author_perspective": "综合",
        "tags": ["庄家思维", "阴谋论", "中国特色"],
        "key_concepts": ["Market Maker Mindset", "Conspiracy Theory", "China-Specific"],
        "case_study": "\"都是庄家控制\"的信念危害",
    },
    "2025-08-21": {
        "title": "\"政策市\"信念的双刃剑",
        "slug": "policy-market-belief",
        "author_perspective": "综合",
        "tags": ["政策市", "外部归因", "控制幻觉"],
        "key_concepts": ["Policy Market", "External Attribution", "Illusion of Control"],
        "case_study": "\"等政策\"心态的陷阱",
    },
    "2025-08-22": {
        "title": "\"散户必亏\"的自我实现",
        "slug": "retail-must-lose-belief",
        "author_perspective": "综合",
        "tags": ["宿命论", "自我实现", "受害者心态"],
        "key_concepts": ["Fatalism", "Self-Fulfillment", "Victim Mentality"],
        "case_study": "\"韭菜\"身份认同的危害",
    },
    "2025-08-23": {
        "title": "交易哲学的建立",
        "slug": "trading-philosophy-establishment",
        "author_perspective": "综合",
        "tags": ["交易哲学", "价值观", "指导原则"],
        "key_concepts": ["Trading Philosophy", "Values", "Guiding Principles"],
        "case_study": "你的交易宪法",
    },
    "2025-08-24": {
        "title": "道家思想与交易",
        "slug": "taoism-trading",
        "author_perspective": "东方哲学",
        "tags": ["道家", "无为", "顺势"],
        "key_concepts": ["Taoism", "Wu Wei", "Following Trends"],
        "case_study": "\"无为而治\"的交易智慧",
    },
    "2025-08-25": {
        "title": "佛学正念与交易觉察",
        "slug": "buddhism-mindfulness-trading",
        "author_perspective": "东方哲学",
        "tags": ["佛学", "正念", "觉察"],
        "key_concepts": ["Buddhism", "Mindfulness", "Awareness"],
        "case_study": "\"当下\"的交易智慧",
    },
    "2025-08-26": {
        "title": "斯多葛主义与交易韧性",
        "slug": "stoicism-trading-resilience",
        "author_perspective": "西方哲学",
        "tags": ["斯多葛", "韧性", "控制二分法"],
        "key_concepts": ["Stoicism", "Resilience", "Dichotomy of Control"],
        "case_study": "\"控制可控，接受不可控\"",
    },
    "2025-08-27": {
        "title": "实用主义与交易实践",
        "slug": "pragmatism-trading-practice",
        "author_perspective": "西方哲学",
        "tags": ["实用主义", "以果为真", "实践检验"],
        "key_concepts": ["Pragmatism", "Truth by Results", "Practice Testing"],
        "case_study": "\"有效即真理\"的交易观",
    },
    "2025-08-28": {
        "title": "存在主义与交易责任",
        "slug": "existentialism-trading-responsibility",
        "author_perspective": "西方哲学",
        "tags": ["存在主义", "自由", "责任"],
        "key_concepts": ["Existentialism", "Freedom", "Responsibility"],
        "case_study": "\"选择即自我\"",
    },
    "2025-08-29": {
        "title": "信念审计：年度大检查",
        "slug": "belief-audit-annual",
        "author_perspective": "综合",
        "tags": ["信念审计", "系统检查", "更新迭代"],
        "key_concepts": ["Belief Audit", "System Check", "Update Iteration"],
        "case_study": "列出你的20条交易信念",
    },
    "2025-08-30": {
        "title": "信念日志：追踪思维模式",
        "slug": "belief-journaling",
        "author_perspective": "Jared Tendler",
        "tags": ["信念日志", "模式追踪", "自我觉察"],
        "key_concepts": ["Belief Journaling", "Pattern Tracking", "Self-Awareness"],
        "case_study": "\"我今天的决策受什么信念驱动\"",
    },
    "2025-08-31": {
        "title": "8月总结：重写你的交易信念系统",
        "slug": "august-summary-rewrite-beliefs",
        "author_perspective": "综合",
        "tags": ["月度总结", "信念系统", "哲学整合"],
        "key_concepts": ["Summary", "Belief System", "Philosophy Integration"],
        "case_study": "你的交易信念2.0版本",
    },
}

# ========== 9月：压力管理与心理韧性（30篇）==========
SEPTEMBER_TOPICS = {
    "2025-09-01": {
        "title": "压力的双面性：敌人还是盟友",
        "slug": "stress-dual-nature",
        "author_perspective": "压力心理学",
        "tags": ["压力", "双面性", "适度压力"],
        "key_concepts": ["Stress", "Dual Nature", "Optimal Stress"],
        "case_study": "耶克斯-多德森定律在交易中的体现",
    },
    "2025-09-02": {
        "title": "急性压力vs慢性压力",
        "slug": "acute-vs-chronic-stress",
        "author_perspective": "健康心理学",
        "tags": ["急性压力", "慢性压力", "健康影响"],
        "key_concepts": ["Acute Stress", "Chronic Stress", "Health Impact"],
        "case_study": "单次暴跌vs持续震荡的不同伤害",
    },
    "2025-09-03": {
        "title": "压力的生理机制",
        "slug": "stress-physiological-mechanism",
        "author_perspective": "Denise Shull",
        "tags": ["生理机制", "皮质醇", "战或逃"],
        "key_concepts": ["Physiological Mechanism", "Cortisol", "Fight-or-Flight"],
        "case_study": "账户暴跌时的身体反应链",
    },
    "2025-09-04": {
        "title": "交易中的压力源识别",
        "slug": "trading-stressors-identification",
        "author_perspective": "Brett Steenbarger",
        "tags": ["压力源", "识别", "分类"],
        "key_concepts": ["Stressors", "Identification", "Classification"],
        "case_study": "你的前10大交易压力源",
    },
    "2025-09-05": {
        "title": "绩效压力：自我施压的陷阱",
        "slug": "performance-pressure-trap",
        "author_perspective": "运动心理学",
        "tags": ["绩效压力", "自我期待", "窒息效应"],
        "key_concepts": ["Performance Pressure", "Self-Expectation", "Choking Effect"],
        "case_study": "\"这个月必须盈利\"的反作用",
    },
    "2025-09-06": {
        "title": "社会压力：\"别人的眼光\"",
        "slug": "social-pressure-others-eyes",
        "author_perspective": "社会心理学",
        "tags": ["社会压力", "评价焦虑", "面子"],
        "key_concepts": ["Social Pressure", "Evaluation Anxiety", "Face"],
        "case_study": "\"不能让人知道我亏了\"",
    },
    "2025-09-07": {
        "title": "财务压力：生存威胁的放大器",
        "slug": "financial-pressure-amplifier",
        "author_perspective": "综合",
        "tags": ["财务压力", "生存焦虑", "决策损害"],
        "key_concepts": ["Financial Pressure", "Survival Anxiety", "Decision Impairment"],
        "case_study": "\"输不起\"如何摧毁交易",
    },
    "2025-09-08": {
        "title": "时间压力：\"必须今天赚到\"",
        "slug": "time-pressure-urgency",
        "author_perspective": "Jared Tendler",
        "tags": ["时间压力", "紧迫感", "冲动"],
        "key_concepts": ["Time Pressure", "Urgency", "Impulsivity"],
        "case_study": "月末还贷的交易扭曲",
    },
    "2025-09-09": {
        "title": "信息过载压力",
        "slug": "information-overload-stress",
        "author_perspective": "认知心理学",
        "tags": ["信息过载", "决策疲劳", "分析瘫痪"],
        "key_concepts": ["Information Overload", "Decision Fatigue", "Analysis Paralysis"],
        "case_study": "同时看20个指标的焦虑",
    },
    "2025-09-10": {
        "title": "不确定性压力：控制的幻灭",
        "slug": "uncertainty-stress",
        "author_perspective": "Mark Douglas",
        "tags": ["不确定性", "控制需求", "接纳"],
        "key_concepts": ["Uncertainty", "Need for Control", "Acceptance"],
        "case_study": "\"不知道明天会怎样\"的煎熬",
    },
    "2025-09-11": {
        "title": "压力管理的四R模型",
        "slug": "four-r-stress-management",
        "author_perspective": "压力管理理论",
        "tags": ["4R模型", "系统管理", "全面应对"],
        "key_concepts": ["4R Model", "Systematic Management", "Comprehensive Response"],
        "case_study": "Recognition-Resistance-Relaxation-Release",
    },
    "2025-09-12": {
        "title": "呼吸技术：最被低估的工具",
        "slug": "breathing-techniques-underrated",
        "author_perspective": "Denise Shull",
        "tags": ["呼吸技术", "副交感神经", "即时缓解"],
        "key_concepts": ["Breathing Techniques", "Parasympathetic", "Immediate Relief"],
        "case_study": "4-7-8呼吸法在盘中的应用",
    },
    "2025-09-13": {
        "title": "正念冥想：训练抗压大脑",
        "slug": "mindfulness-meditation-resilient-brain",
        "author_perspective": "神经科学",
        "tags": ["正念冥想", "大脑可塑性", "压力韧性"],
        "key_concepts": ["Mindfulness Meditation", "Neuroplasticity", "Stress Resilience"],
        "case_study": "8周冥想改变杏仁核体积",
    },
    "2025-09-14": {
        "title": "运动：压力的物理释放",
        "slug": "exercise-physical-stress-release",
        "author_perspective": "运动心理学",
        "tags": ["运动", "内啡肽", "压力释放"],
        "key_concepts": ["Exercise", "Endorphins", "Stress Release"],
        "case_study": "盘后跑步的心理修复",
    },
    "2025-09-15": {
        "title": "睡眠：压力的天然解药",
        "slug": "sleep-natural-stress-remedy",
        "author_perspective": "睡眠科学",
        "tags": ["睡眠", "恢复", "认知功能"],
        "key_concepts": ["Sleep", "Recovery", "Cognitive Function"],
        "case_study": "睡眠不足与交易错误的关联",
    },
    "2025-09-16": {
        "title": "社会支持：不要独自承受",
        "slug": "social-support-dont-bear-alone",
        "author_perspective": "社会心理学",
        "tags": ["社会支持", "情感支持", "孤独危害"],
        "key_concepts": ["Social Support", "Emotional Support", "Loneliness Harm"],
        "case_study": "交易者需要\"树洞\"",
    },
    "2025-09-17": {
        "title": "认知重评：改变压力的意义",
        "slug": "cognitive-reappraisal-stress-meaning",
        "author_perspective": "认知心理学",
        "tags": ["认知重评", "框架重构", "意义赋予"],
        "key_concepts": ["Cognitive Reappraisal", "Reframing", "Meaning Making"],
        "case_study": "\"压力\"变\"挑战\"",
    },
    "2025-09-18": {
        "title": "心理韧性的七大支柱",
        "slug": "seven-pillars-resilience",
        "author_perspective": "积极心理学",
        "tags": ["心理韧性", "支柱", "系统建设"],
        "key_concepts": ["Psychological Resilience", "Pillars", "System Building"],
        "case_study": "韧性评估量表",
    },
    "2025-09-19": {
        "title": "从挫折中恢复：弹性曲线",
        "slug": "recovery-from-setbacks",
        "author_perspective": "Brett Steenbarger",
        "tags": ["挫折恢复", "弹性", "反脆弱"],
        "key_concepts": ["Setback Recovery", "Resilience", "Antifragility"],
        "case_study": "连续亏损后的复原力",
    },
    "2025-09-20": {
        "title": "创伤后成长：亏损的意外礼物",
        "slug": "post-traumatic-growth",
        "author_perspective": "积极心理学",
        "tags": ["创伤后成长", "转化", "深度学习"],
        "key_concepts": ["Post-Traumatic Growth", "Transformation", "Deep Learning"],
        "case_study": "\"那次爆仓让我重生\"",
    },
    "2025-09-21": {
        "title": "成长心态vs固定心态",
        "slug": "growth-vs-fixed-mindset",
        "author_perspective": "Carol Dweck",
        "tags": ["成长心态", "固定心态", "可塑性"],
        "key_concepts": ["Growth Mindset", "Fixed Mindset", "Malleability"],
        "case_study": "\"我天生不适合交易\"vs\"我可以学习\"",
    },
    "2025-09-22": {
        "title": "自我同情：对自己温柔点",
        "slug": "self-compassion-be-gentle",
        "author_perspective": "Kristin Neff",
        "tags": ["自我同情", "自我批判", "温柔"],
        "key_concepts": ["Self-Compassion", "Self-Criticism", "Gentleness"],
        "case_study": "\"我又犯错了\"vs\"我正在学习\"",
    },
    "2025-09-23": {
        "title": "幽默感：压力的缓冲器",
        "slug": "humor-stress-buffer",
        "author_perspective": "积极心理学",
        "tags": ["幽默感", "视角转换", "轻松化"],
        "key_concepts": ["Humor", "Perspective Shift", "Lightening"],
        "case_study": "\"自嘲\"的心理保护作用",
    },
    "2025-09-24": {
        "title": "意义感：\"为什么\"的力量",
        "slug": "sense-of-meaning-why-power",
        "author_perspective": "Viktor Frankl",
        "tags": ["意义感", "目的", "动机"],
        "key_concepts": ["Sense of Meaning", "Purpose", "Motivation"],
        "case_study": "\"我为什么要交易\"",
    },
    "2025-09-25": {
        "title": "中国交易者的特殊压力",
        "slug": "chinese-traders-unique-stress",
        "author_perspective": "综合",
        "tags": ["中国特色", "文化压力", "社会期待"],
        "key_concepts": ["China-Specific", "Cultural Pressure", "Social Expectation"],
        "case_study": "\"30岁还在炒股\"的社会压力",
    },
    "2025-09-26": {
        "title": "\"输不起\"文化的心理负担",
        "slug": "cant-lose-culture-burden",
        "author_perspective": "综合",
        "tags": ["输不起", "面子文化", "压力源"],
        "key_concepts": ["Can't Lose", "Face Culture", "Stress Source"],
        "case_study": "\"成功学\"如何制造交易压力",
    },
    "2025-09-27": {
        "title": "压力与创造力的U型曲线",
        "slug": "stress-creativity-u-curve",
        "author_perspective": "创造力心理学",
        "tags": ["压力曲线", "创造力", "最佳点"],
        "key_concepts": ["Stress Curve", "Creativity", "Sweet Spot"],
        "case_study": "适度紧张带来最佳表现",
    },
    "2025-09-28": {
        "title": "长期主义：对抗短期压力",
        "slug": "long-termism-vs-short-term-stress",
        "author_perspective": "综合",
        "tags": ["长期主义", "时间视角", "压力消解"],
        "key_concepts": ["Long-termism", "Time Perspective", "Stress Dissolution"],
        "case_study": "\"5年后看今天的亏损\"",
    },
    "2025-09-29": {
        "title": "建立你的压力仪表盘",
        "slug": "build-stress-dashboard",
        "author_perspective": "Brett Steenbarger",
        "tags": ["压力监测", "仪表盘", "自我觉察"],
        "key_concepts": ["Stress Monitoring", "Dashboard", "Self-Awareness"],
        "case_study": "7个指标实时监测压力水平",
    },
    "2025-09-30": {
        "title": "9月总结：成为压力下的表演者",
        "slug": "september-summary-performer-under-pressure",
        "author_perspective": "综合",
        "tags": ["月度总结", "压力管理", "韧性系统"],
        "key_concepts": ["Summary", "Stress Management", "Resilience System"],
        "case_study": "你的抗压工具箱",
    },
}

# ========== 10月：影响力与社会心理（31篇）==========
OCTOBER_TOPICS = {
    "2025-10-01": {
        "title": "市场是最大的社会心理实验室",
        "slug": "market-social-psychology-lab",
        "author_perspective": "Robert Cialdini",
        "tags": ["社会心理", "市场行为", "群体动力"],
        "key_concepts": ["Social Psychology", "Market Behavior", "Group Dynamics"],
        "case_study": "牛市中的集体疯狂",
    },
    "2025-10-02": {
        "title": "社会认同原理深度解析",
        "slug": "social-proof-deep-dive",
        "author_perspective": "Robert Cialdini",
        "tags": ["社会认同", "从众", "信息瀑布"],
        "key_concepts": ["Social Proof", "Conformity", "Information Cascade"],
        "case_study": "\"龙头股\"效应的心理机制",
    },
    "2025-10-03": {
        "title": "羊群效应的三个阶段",
        "slug": "herd-behavior-three-stages",
        "author_perspective": "行为金融学",
        "tags": ["羊群效应", "阶段", "演化"],
        "key_concepts": ["Herd Behavior", "Stages", "Evolution"],
        "case_study": "从\"理性跟随\"到\"非理性狂热\"",
    },
    "2025-10-04": {
        "title": "信息瀑布：真相的淹没",
        "slug": "information-cascade-truth-drowning",
        "author_perspective": "信息经济学",
        "tags": ["信息瀑布", "真相", "跟随"],
        "key_concepts": ["Information Cascade", "Truth", "Following"],
        "case_study": "\"大家都在买\"掩盖了什么",
    },
    "2025-10-05": {
        "title": "权威的力量与盲点",
        "slug": "authority-power-blindspot",
        "author_perspective": "Robert Cialdini",
        "tags": ["权威", "服从", "米尔格拉姆"],
        "key_concepts": ["Authority", "Obedience", "Milgram"],
        "case_study": "\"专家\"说的就一定对？",
    },
    "2025-10-06": {
        "title": "假专家的识别",
        "slug": "fake-expert-identification",
        "author_perspective": "批判性思维",
        "tags": ["假专家", "识别", "独立判断"],
        "key_concepts": ["Fake Expert", "Identification", "Independent Judgment"],
        "case_study": "股评家的\"专业\"表演",
    },
    "2025-10-07": {
        "title": "网红经济与交易决策",
        "slug": "influencer-economy-trading",
        "author_perspective": "综合",
        "tags": ["网红经济", "影响力", "盲从"],
        "key_concepts": ["Influencer Economy", "Influence", "Blind Following"],
        "case_study": "\"财经网红\"带货式荐股",
    },
    "2025-10-08": {
        "title": "互惠原理在交易中的陷阱",
        "slug": "reciprocity-trading-trap",
        "author_perspective": "Robert Cialdini",
        "tags": ["互惠原理", "人情债", "陷阱"],
        "key_concepts": ["Reciprocity", "Social Debt", "Trap"],
        "case_study": "\"免费\"的代价",
    },
    "2025-10-09": {
        "title": "承诺一致性的威力",
        "slug": "commitment-consistency-power",
        "author_perspective": "Robert Cialdini",
        "tags": ["承诺一致", "认知协调", "路径依赖"],
        "key_concepts": ["Commitment Consistency", "Cognitive Harmony", "Path Dependence"],
        "case_study": "\"我公开说看多了\"的后续压力",
    },
    "2025-10-10": {
        "title": "喜好原理：\"我喜欢他所以信他\"",
        "slug": "liking-principle-trust",
        "author_perspective": "Robert Cialdini",
        "tags": ["喜好原理", "信任", "非理性"],
        "key_concepts": ["Liking Principle", "Trust", "Irrationality"],
        "case_study": "外表、相似性、赞美的影响力",
    },
    "2025-10-11": {
        "title": "稀缺性制造紧迫感",
        "slug": "scarcity-creates-urgency",
        "author_perspective": "Robert Cialdini",
        "tags": ["稀缺性", "紧迫感", "FOMO"],
        "key_concepts": ["Scarcity", "Urgency", "FOMO"],
        "case_study": "\"最后上车机会\"的营销术",
    },
    "2025-10-12": {
        "title": "群体极化：讨论让人更极端",
        "slug": "group-polarization-extreme",
        "author_perspective": "社会心理学",
        "tags": ["群体极化", "讨论", "极端化"],
        "key_concepts": ["Group Polarization", "Discussion", "Extremization"],
        "case_study": "股吧如何制造\"一致看多\"",
    },
    "2025-10-13": {
        "title": "回音室效应：信息茧房",
        "slug": "echo-chamber-effect",
        "author_perspective": "媒体心理学",
        "tags": ["回音室", "信息茧房", "认知封闭"],
        "key_concepts": ["Echo Chamber", "Filter Bubble", "Cognitive Closure"],
        "case_study": "算法如何强化你的偏见",
    },
    "2025-10-14": {
        "title": "去个性化：群体中的匿名性",
        "slug": "deindividuation-anonymity",
        "author_perspective": "社会心理学",
        "tags": ["去个性化", "匿名性", "群体行为"],
        "key_concepts": ["Deindividuation", "Anonymity", "Crowd Behavior"],
        "case_study": "网络暴民的心理机制",
    },
    "2025-10-15": {
        "title": "社会比较：向上vs向下",
        "slug": "social-comparison-upward-downward",
        "author_perspective": "社会心理学",
        "tags": ["社会比较", "攀比", "自尊"],
        "key_concepts": ["Social Comparison", "Rivalry", "Self-Esteem"],
        "case_study": "\"别人都赚了，就我亏\"",
    },
    "2025-10-16": {
        "title": "相对剥夺感：\"不患寡而患不均\"",
        "slug": "relative-deprivation",
        "author_perspective": "社会心理学",
        "tags": ["相对剥夺", "公平感", "愤怒"],
        "key_concepts": ["Relative Deprivation", "Fairness", "Anger"],
        "case_study": "牛市中为何还有人愤怒",
    },
    "2025-10-17": {
        "title": "从众的三种类型",
        "slug": "three-types-conformity",
        "author_perspective": "社会心理学",
        "tags": ["从众类型", "服从", "认同"],
        "key_concepts": ["Conformity Types", "Compliance", "Identification"],
        "case_study": "表面跟随vs内心认同",
    },
    "2025-10-18": {
        "title": "少数派影响力",
        "slug": "minority-influence",
        "author_perspective": "社会心理学",
        "tags": ["少数派", "坚持", "创新"],
        "key_concepts": ["Minority", "Persistence", "Innovation"],
        "case_study": "\"逆向投资者\"的心理韧性",
    },
    "2025-10-19": {
        "title": "群体思维：一致性的陷阱",
        "slug": "groupthink-consensus-trap",
        "author_perspective": "Irving Janis",
        "tags": ["群体思维", "一致性", "决策失误"],
        "key_concepts": ["Groupthink", "Consensus", "Decision Failure"],
        "case_study": "投资委员会的灾难性决策",
    },
    "2025-10-20": {
        "title": "社交媒体时代的交易心理",
        "slug": "social-media-trading-psychology",
        "author_perspective": "综合",
        "tags": ["社交媒体", "即时反馈", "炫耀"],
        "key_concepts": ["Social Media", "Instant Feedback", "Showing Off"],
        "case_study": "\"晒单\"文化的心理学",
    },
    "2025-10-21": {
        "title": "FOMO的社会根源",
        "slug": "fomo-social-roots",
        "author_perspective": "综合",
        "tags": ["FOMO", "社会根源", "进化心理"],
        "key_concepts": ["FOMO", "Social Roots", "Evolutionary Psychology"],
        "case_study": "为什么\"别人赚了\"让你难受",
    },
    "2025-10-22": {
        "title": "炫耀性消费vs炫耀性投资",
        "slug": "conspicuous-consumption-investment",
        "author_perspective": "社会学",
        "tags": ["炫耀", "地位", "社会认同"],
        "key_concepts": ["Conspicuous", "Status", "Social Recognition"],
        "case_study": "\"我买了某某股票\"的炫耀",
    },
    "2025-10-23": {
        "title": "中国式关系网与交易",
        "slug": "chinese-guanxi-trading",
        "author_perspective": "综合",
        "tags": ["关系网", "信息获取", "内幕"],
        "key_concepts": ["Guanxi", "Information Access", "Inside Info"],
        "case_study": "\"听朋友说\"的信息陷阱",
    },
    "2025-10-24": {
        "title": "\"消息\"文化的心理基础",
        "slug": "rumor-culture-psychology",
        "author_perspective": "综合",
        "tags": ["消息文化", "信息崇拜", "捷径心理"],
        "key_concepts": ["Rumor Culture", "Information Worship", "Shortcut Mentality"],
        "case_study": "为什么中国散户特别爱\"打听\"",
    },
    "2025-10-25": {
        "title": "集体记忆与市场叙事",
        "slug": "collective-memory-market-narrative",
        "author_perspective": "社会学",
        "tags": ["集体记忆", "叙事", "历史"],
        "key_concepts": ["Collective Memory", "Narrative", "History"],
        "case_study": "\"这次和2007/2015年一样\"",
    },
    "2025-10-26": {
        "title": "代际差异：60后、80后、00后交易者",
        "slug": "generational-differences-traders",
        "author_perspective": "社会学",
        "tags": ["代际差异", "价值观", "行为模式"],
        "key_concepts": ["Generational Difference", "Values", "Behavior Pattern"],
        "case_study": "不同年代人的风险偏好",
    },
    "2025-10-27": {
        "title": "独立思考的社会成本",
        "slug": "independent-thinking-social-cost",
        "author_perspective": "综合",
        "tags": ["独立思考", "社会成本", "孤独"],
        "key_concepts": ["Independent Thinking", "Social Cost", "Loneliness"],
        "case_study": "\"逆向\"操作的心理压力",
    },
    "2025-10-28": {
        "title": "如何抵抗社会影响",
        "slug": "resisting-social-influence",
        "author_perspective": "Robert Cialdini",
        "tags": ["抵抗", "免疫", "独立"],
        "key_concepts": ["Resistance", "Immunity", "Independence"],
        "case_study": "心理免疫接种技术",
    },
    "2025-10-29": {
        "title": "建立你的信息防火墙",
        "slug": "information-firewall",
        "author_perspective": "综合",
        "tags": ["信息过滤", "防火墙", "噪音屏蔽"],
        "key_concepts": ["Information Filtering", "Firewall", "Noise Blocking"],
        "case_study": "删除90%的信息源",
    },
    "2025-10-30": {
        "title": "孤独的勇气：交易者的修行",
        "slug": "courage-to-be-lonely",
        "author_perspective": "存在主义",
        "tags": ["孤独", "勇气", "独立"],
        "key_concepts": ["Loneliness", "Courage", "Independence"],
        "case_study": "\"我不需要共识\"",
    },
    "2025-10-31": {
        "title": "10月总结：成为独立的思考者",
        "slug": "october-summary-independent-thinker",
        "author_perspective": "综合",
        "tags": ["月度总结", "独立思考", "影响力免疫"],
        "key_concepts": ["Summary", "Independent Thinking", "Influence Immunity"],
        "case_study": "你的心理防护系统",
    },
}

# ========== 11月1-15日：整合与升华（15篇）==========
NOVEMBER_TOPICS = {
    "2025-11-01": {
        "title": "交易心理学的整合框架",
        "slug": "trading-psychology-integration-framework",
        "author_perspective": "综合",
        "tags": ["整合框架", "系统化", "全局视角"],
        "key_concepts": ["Integration Framework", "Systemization", "Holistic View"],
        "case_study": "10个月学习的知识地图",
    },
    "2025-11-02": {
        "title": "从知道到做到：行为改变的鸿沟",
        "slug": "knowing-doing-gap",
        "author_perspective": "行为改变理论",
        "tags": ["知行合一", "行为改变", "实践"],
        "key_concepts": ["Knowing-Doing Gap", "Behavior Change", "Practice"],
        "case_study": "为什么懂那么多还是亏钱",
    },
    "2025-11-03": {
        "title": "刻意练习：21天到10000小时",
        "slug": "deliberate-practice-mastery",
        "author_perspective": "Anders Ericsson",
        "tags": ["刻意练习", "专精", "长期主义"],
        "key_concepts": ["Deliberate Practice", "Mastery", "Long-term"],
        "case_study": "交易心理技能的训练计划",
    },
    "2025-11-04": {
        "title": "建立你的个人交易心理系统",
        "slug": "personal-trading-psychology-system",
        "author_perspective": "综合",
        "tags": ["个人系统", "定制化", "整合"],
        "key_concepts": ["Personal System", "Customization", "Integration"],
        "case_study": "系统的7个核心模块",
    },
    "2025-11-05": {
        "title": "交易日常：仪式化的力量",
        "slug": "trading-routine-ritualization",
        "author_perspective": "习惯心理学",
        "tags": ["日常仪式", "习惯化", "自动化"],
        "key_concepts": ["Daily Ritual", "Habituation", "Automation"],
        "case_study": "专业交易者的一天",
    },
    "2025-11-06": {
        "title": "持续进化：交易者的终身学习",
        "slug": "continuous-evolution-lifelong-learning",
        "author_perspective": "成长心态",
        "tags": ["持续进化", "终身学习", "自我超越"],
        "key_concepts": ["Continuous Evolution", "Lifelong Learning", "Self-Transcendence"],
        "case_study": "10年交易者还在学什么",
    },
    "2025-11-07": {
        "title": "交易与人生：更大的视角",
        "slug": "trading-and-life-bigger-perspective",
        "author_perspective": "人生哲学",
        "tags": ["人生视角", "意义", "平衡"],
        "key_concepts": ["Life Perspective", "Meaning", "Balance"],
        "case_study": "交易是手段，不是目的",
    },
    "2025-11-08": {
        "title": "失败的价值：最好的老师",
        "slug": "value-of-failure-best-teacher",
        "author_perspective": "成长心态",
        "tags": ["失败价值", "学习", "成长"],
        "key_concepts": ["Failure Value", "Learning", "Growth"],
        "case_study": "我最宝贵的10次亏损",
    },
    "2025-11-09": {
        "title": "交易者的自我关怀",
        "slug": "trader-self-care",
        "author_perspective": "积极心理学",
        "tags": ["自我关怀", "身心健康", "可持续"],
        "key_concepts": ["Self-Care", "Wellbeing", "Sustainability"],
        "case_study": "不要在燃尽中交易",
    },
    "2025-11-10": {
        "title": "传承：成为别人的导师",
        "slug": "legacy-becoming-mentor",
        "author_perspective": "综合",
        "tags": ["传承", "导师", "回馈"],
        "key_concepts": ["Legacy", "Mentorship", "Giving Back"],
        "case_study": "教学相长的智慧",
    },
    "2025-11-11": {
        "title": "中国交易者的未来",
        "slug": "future-chinese-traders",
        "author_perspective": "综合",
        "tags": ["未来展望", "中国市场", "进化"],
        "key_concepts": ["Future Outlook", "China Market", "Evolution"],
        "case_study": "从投机到投资的文化转型",
    },
    "2025-11-12": {
        "title": "交易心理学的边界",
        "slug": "boundaries-trading-psychology",
        "author_perspective": "综合",
        "tags": ["边界", "局限", "整合"],
        "key_concepts": ["Boundaries", "Limitations", "Integration"],
        "case_study": "心理不是万能的，但不可或缺",
    },
    "2025-11-13": {
        "title": "终极问题：你为什么交易",
        "slug": "ultimate-question-why-trade",
        "author_perspective": "存在主义",
        "tags": ["终极问题", "动机", "意义"],
        "key_concepts": ["Ultimate Question", "Motivation", "Meaning"],
        "case_study": "深挖你的真实动机",
    },
    "2025-11-14": {
        "title": "感恩之旅：319天的回顾",
        "slug": "gratitude-journey-319-days",
        "author_perspective": "综合",
        "tags": ["感恩", "回顾", "总结"],
        "key_concepts": ["Gratitude", "Review", "Summary"],
        "case_study": "这319篇文章改变了什么",
    },
    "2025-11-15": {
        "title": "新的开始：终点即起点",
        "slug": "new-beginning-end-is-start",
        "author_perspective": "综合",
        "tags": ["新开始", "持续旅程", "承诺"],
        "key_concepts": ["New Beginning", "Continuous Journey", "Commitment"],
        "case_study": "今天是你交易心理修炼的第一天",
    },
}

# 导出所有主题
ALL_TOPICS_AUG_NOV = {}
ALL_TOPICS_AUG_NOV.update(AUGUST_TOPICS)
ALL_TOPICS_AUG_NOV.update(SEPTEMBER_TOPICS)
ALL_TOPICS_AUG_NOV.update(OCTOBER_TOPICS)
ALL_TOPICS_AUG_NOV.update(NOVEMBER_TOPICS)

if __name__ == "__main__":
    print(f"8-11月主题总数: {len(ALL_TOPICS_AUG_NOV)}")
    print(f"8月: {len(AUGUST_TOPICS)}")
    print(f"9月: {len(SEPTEMBER_TOPICS)}")
    print(f"10月: {len(OCTOBER_TOPICS)}")
    print(f"11月1-15日: {len(NOVEMBER_TOPICS)}")
